export const LOAD_CHARACTERS = 'LOAD_CHARACTERS'
export const LOADING_FETCH = 'LOADING_FETCH'
export const DISPLAY_MORE_INFOS = 'DISPLAY_MORE_INFOS'
export const CHANGE_CHARACTER_ID = 'CHANGE_CHARACTER_ID'


